Features/si 7124 onboarding screen/si 7126 main screen
AliceGera/mobidoc pull request #2
Opened 2023-11-17 22:16 UTC by AliceGera

2023-11-17 22:31 UTC, AliceGera commented
https://github.com/AliceGera/mobidoc/assets/96451580/8ba4fa37-e655-4f62-b53c-4f3b44b68b1f

2023-11-22 09:38 UTC, roketstorm requested changes

2023-11-22 09:38 UTC, roketstorm commented on lib/features/common/widgets/app_button_widget.dart
> +        backgroundColor: MaterialStateProperty.all<Color>(const Color(0xff007AFE)),
Лучше вывести константы по цветам в отдельный файлик

2023-11-22 09:38 UTC, roketstorm commented on lib/features/medical_card/screens/onboarding_screen/onboarding_screen.dart
> +                              : '',
Слишком глубокий каскад. Можно переделать через switch-case

2023-11-22 12:14 UTC, merged